import 'dart:async';
import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

import '../dao/item_dao.dart';
import '../model/item_model.dart';
import '../dao/category_dao.dart'; 

// part 'local.g.dart'; // This will be generated by Floor
part 'local.g.dart';

@Database(version: 1, entities: [ItemModel]) // TODO: Add category, notifications, repeat
abstract class AppDatabase extends FloorDatabase {
  ItemDao get itemDao;
  // CategoryDao get categoryDao;
}